### PR TITLE
Chinese translations update

### PR DESCRIPTION
**Pull request by ChuijkYahus**
_Sorry if my English reads weird_
There are a few catches about the latest update of Chinese translations and I've also got some translation bumps while doing reaearch. Also if there's any problem about this version of translations please notify me, a comment under this pr will do.

Foxnip -> 薄荷(lit. mint), the new one is 狐金香(fox tulip).

There's a bump on "-nip" part because I couldn't find a proper meaning of it. _ended up choosing "-lip" in tulip though Foxnips are unlikely to be tulips._

Pulse Petal -> 剪秋罗([wikipedia](https://en.wikipedia.org/wiki/Silene_sieboldii)), the new one is 脉冲花(lit. pulse flower).

Fairy Blossom -> 康乃馨(lit. carnation), the new one is 精灵花(lit. fairy flower).

Gem of the Jungle -> 金盏花(lit. marigold), the new one is 丛林之珍(lit. gem/pearl/treasure of the jungle).

玫瑰 and 蔷薇 are all common names for roses in Chinese, yet Rose Bush in Vanilla is translated as 玫瑰丛.

Sunset Poppy: sunset maybe referencing to the color of sunset(sunset glow as in 晚霞), poppy is re-translated into 虞美人 in Chinese since 1.9 to 1.12 because 罂粟 usually takes the meaning of opium.

Muscari -> 勿忘我(lit. forget me not), the new one is 葡萄风信子, which translates to muscari.

Scilla is more commonly called 绵枣儿 rather than 独叶地兰.

Potted flowers in Chinese has 盆栽 after their names.

Purpureum is the largest bump. I can't find it's corresponding species irl, so I chose one of wikipedia's entries on purpureum as Thomasia purpurea. The flower irl is native to southwest Australia, yet Purpurea is grown in swampy biomes(maybe). Please notify me if there's a real-life correspondence or a better understanding of the name.

### CODE REVIEW

**Comment by ChuijkYahus** [comment]
The original pr of Floral Flair's Chinese translation into a CHN language resourcepack here.
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1579
This is an earlier version of the mod, the translations weren't pushed here because I found several new textures of new flowers.

**Comment by ManaStar** [comment]
Purpureums ingame are based off of the Eutrochium purpureum, also known as the "Joe Pye weed." However the swamp part was mainly picked due to the colours fitting well with the biome

**Comment by ChuijkYahus** [comment]
Purpureums' translations changed.
The translations are from this site built by the Chinese Academy of Sciences, [link](http://www.iplant.cn/info/eutrochium%20purpureum).
Also, may I ask if there's a need of changing Foxnips' trsls or those of other flowers.

Really appreciate your great mod and your help on trsls.

**Comment by ManaStar** [comment]
The Foxnip translation seems good, it means a lot that you are helping with this! Do you think the translations of the fantasy flowers like the Stonnete or the Spiked Tulip are appropriate as well? I don't quite know what they translate into so I am curious if they fit the plants.

**Comment by ChuijkYahus** [comment]
All of them are good to me.
Stonnetes' name 石之芯 actually means 'heart of the stones' or 'middle part of the stone', sounds great though.
Don't know if Pulse Petals have a real-life correspondence.

Anthurium can be translated into 红掌, 红花烛, 火鹤红（掌）, so I think its trsls are OK.

**Comment by ManaStar** [comment]
Since everything seems to be in order I think I am going to merge this, I very much appreciate your help with this!

**Comment by ChuijkYahus** [comment]
Really appreciate the great mod!

Also may I ask about how can I contact the former translator.
The trsls are also getting pushed to the CHN language resourcepack and I wish to label him/her as a co-author.

**Comment by Ibex80** [comment]
> Really appreciate the great mod!
> 
> 
> 
> Also may I ask about how can I contact the former translator.
> 
> The trsls are also getting pushed to the CHN language resourcepack and I wish to label him/her as a co-author.

Their discord handle is **chen_index#0390**.

**Comment by ChuijkYahus** [comment]
> > Really appreciate the great mod!
> > Also may I ask about how can I contact the former translator.
> > The trsls are also getting pushed to the CHN language resourcepack and I wish to label him/her as a co-author.
> 
> Their discord handle is **chen_index#0390**.

thanks a lot

**Pull request merged**
